#!name = Reddit NSFW解除 + 广告过滤
#!desc = 拦截 gql-fed.reddit.com 响应，isNsfw 强制置 false，并过滤 feed 中的推广/广告节点
#!author = 77bond
#!homepage = https://github.com/77bond/QXrepo

[rewrite_local]
^https:\/\/gql-fed\.reddit\.com\/ url script-response-body https://raw.githubusercontent.com/77bond/QXrepo/main/Reddit/reddit_isNsfw.js
